// Step definitions generated by "Scaffold missing steps".
// Locators belong on the page object, not here — see the imports below.


import { createBdd } from 'playwright-bdd';
import { LoginPage } from '../../pages/oc-login/LoginPage';
import { DashboardPage } from '../../pages/oc-login/DashboardPage';

const { When, Then } = createBdd(undefined, { tags: '@oc-login' });

When('the user closes the initial overlay', async ({ page }) => {
  await new LoginPage(page).closeInitialOverlay();
});

When('the user logs in as {string} with password {string} with remember me checked', async ({ page }, username: string, password: string) => {
  await new LoginPage(page).loginWithRememberMe(username, password);
});

When('the user selects the user {string}', async ({ page }, name: string) => {
  await new DashboardPage(page).selectUser(name);
});

When('the user signs out', async ({ page }) => {
  await new DashboardPage(page).signOut();
});

Then('the login page should match its visual baseline', async ({ page }) => {
  await new LoginPage(page).expectVisualBaseline();
});
