// Step definitions generated by "Scaffold missing steps".
// Locators belong on the page object, not here — see the imports below.


import { createBdd } from 'playwright-bdd';
import { OcLoginPage } from '../../pages/oc-login/OcLoginPage';

const { Given, When, Then } = createBdd(undefined, { tags: '@oc-login' });

Given('I am on the testai login page', async ({ page }) => {
  await new OcLoginPage(page).open();
});

When('I enter username {string} and password {string}', async ({ page }, username: string, password: string) => {
  await new OcLoginPage(page).enterCredentials(username, password);
});

When('I check the Remember Me checkbox', async ({ page }) => {
  await new OcLoginPage(page).checkRememberMe();
});

When('I click the Sign In button', async ({ page }) => {
  await new OcLoginPage(page).clickSignIn();
});

Then('I should be logged in', async ({ page }) => {
  await new OcLoginPage(page).expectLoggedIn();
});

When('I click the user menu', async ({ page }) => {
  await new OcLoginPage(page).openUserMenu();
});

When('I click Sign Out', async ({ page }) => {
  await new OcLoginPage(page).clickSignOut();
});

Then('I should be on the login page', async ({ page }) => {
  await new OcLoginPage(page).expectOnLoginPage();
});
