// Step definitions generated by "Scaffold missing steps".
// Locators belong on the page object, not here — see the imports below.


import { createBdd } from 'playwright-bdd';
import { LoginPage } from '../../pages/ordercircle-signup/LoginPage';
import { ProductsPage } from '../../pages/ordercircle-signup/ProductsPage';

const { Given, When, Then } = createBdd(undefined, { tags: '@ordercircle-signup' });

Given('I am logged in as admin', async ({ page }) => {
  // Credentials from the OC-signup user story.
  await new LoginPage(page).login('admin', 'Test123!');
});

When('I navigate to the Products page', async ({ page }) => {
  await new ProductsPage(page).open();
});

When('I click the {string} button', async ({ page }, name: string) => {
  await new ProductsPage(page).clickButton(name);
});

When('I enter the product name {string}', async ({ page }, name: string) => {
  await new ProductsPage(page).enterProductName(name);
});

When('I enter the product SKU {string}', async ({ page }, sku: string) => {
  await new ProductsPage(page).enterProductSku(sku);
});

When('I enable the inventory tracking feature', async ({ page }) => {
  await new ProductsPage(page).enableInventoryTracking();
});

When('I set the inventory level to {string}', async ({ page }, level: string) => {
  await new ProductsPage(page).setInventoryLevel(level);
});

Then('the product form should be displayed', async ({ page }) => {
  await new ProductsPage(page).expectFormDisplayed();
});
